### ISSUE TITLE
numbers between 0 and 1 (exclusive) should drop leading 0

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-codegen-js#15]
`0.5` should be rendered as `.5`, but is currently rendered as `0.5`.

**Comment by ikarienator** [comment]
It's currently using `D2A`. We need a `MinimalD2A` infrastructure.

**Comment by michaelficarra** [comment]
Fixed by https://github.com/shapesecurity/shift-codegen-js/commit/1c29598aa10a5a4c102d768b56de3e99addd91f5.
