### ISSUE TITLE
TypeError: Cannot call method 'emit' of undefined

### ISSUE THREAD

**Issue by tolmasky** [shapesecurity/shift-codegen-js#21]
Not sure if I'm missing something, but with the latest:

> npm install shift-parser
> npm install shift-codegen
> node
> require("shift-codegen").default(require("shift-parser").default("x = 10"))
> TypeError: Cannot call method 'emit' of undefined

**Comment by michaelficarra** [comment]
Sorry, it's because you're using the latest version of the parser and an old version of the code generator. I forgot to release the latest code generator. Should be fixed now that 3.0.0 is published.
