### ISSUE TITLE
code formatting options

### ISSUE THREAD

**Issue by drom** [shapesecurity/shift-codegen-js#26]
I can't find description of any code formatting options in `shift-codegen-js`. It would be nice to have something like `escodegen` options.

**Comment by michaelficarra** [comment]
Yes, this implementation has no formatting options. It will only generate the minimum necessary syntax (as would be used by a minifier). The implementation in [shift-java](https://github.com/shapesecurity/shift-java) has extensible formatting, and has two formatters: minimal and human-readable. I'd accept a PR that added that feature to shift-codegen-js.

**Comment by drom** [comment]
Related to the shift-java: https://github.com/shapesecurity/shift-java/issues/77
Back to JS. Would you imagine having formatting options similar to `escodegen` or somewhat different?

**Comment by michaelficarra** [comment]
I don't think we are interested in the kind of granularity that escodegen gives you. Simply having "minimal" and "human-readable" options is fine for now, and we can explore making a "pretty" formatter that is configurable after that.

**Comment by michaelficarra** [comment]
This was fixed by #28. Closing.
