### ISSUE TITLE
Invalid output for negative numeric object properties

### ISSUE THREAD

**Issue by dfreeman** [shapesecurity/shift-codegen-js#38]
When an object property has a name that looks like a negative number, the resulting generated code fails to quote the key. For instance, the following AST would generate the invalid expression `{-5:true}`.

``` js
{
  type: "ObjectExpression",
  properties: [
    {
      type: "DataProperty",
      name: {
        type: "StaticPropertyName",
        value: "-5"
      },
      expression: {
        type: "LiteralBooleanExpression",
        value: true
      }
    }
  ]
}
```

**Comment by bakkot** [comment]
Thanks, good catch. This will be fixed in the next release.
