### ISSUE TITLE
Node to string index mappings

### ISSUE THREAD

**Issue by mightyiam** [shapesecurity/shift-codegen-js#66]
I start by using the [fuzzer](https://github.com/shapesecurity/shift-fuzzer-js) to generate some random AST.

Then, I would like to render this AST as code on a web page and have "references" between the code and the AST nodes that they represent. So, for example, the user could cause a specific AST node's representative code to highlight. For demonstration, see how the https://astexplorer.net/ highlights code when the mouse is over a node in the tree.

I went over the code of the codegen (this project) and stepped threw it for a while with a debugger. From what I understand, there is no quick trick to accomplish this. The CodeGen would have to add references to the [`rep`](https://github.com/shapesecurity/shift-codegen-js/blob/f493e4ae0240198a995a78976ba4c4ba75413877/src/index.js#L7) (what does `rep` stand for, please?) and the TokenStream would have to instrument those referenced AST nodes with `start` and `end` indexes, or alternatively, produce a separate map between AST nodes and their `start`/`end` values. BTW, I like the non-mutating nature of the latter approach.

Of course, another approach would be to parse the resulting string of code back to an AST using the parser and have the parser include `start`/`end` properties in the resulting AST nods. Different parsers do this. You can see examples in the https://astexplorer.net/. For me, because my code currently starts as an AST from the fuzzer, I don't need to include a parser in my web bundle. I have a preference of keeping it this way, for loading times.

Any thoughts?

**Comment by bakkot** [comment]
>  The CodeGen would have to add references to the rep (what does rep stand for, please?) and the TokenStream would have to [...] produce a separate map between AST nodes and their start/end values

This is the approach [taken](https://github.com/shapesecurity/shift-java/pull/136/files) in shift-java, which exposes a `codeGenWithLocation` which mirrors the `parseScriptWithLocation` API the parser currently exposes. It's a good idea, but not currently implemented in this project. It might be a little easier to do in JS than it was in Java, at least.

> Of course, another approach would be to parse the resulting string of code back to an AST using the parser and have the parser include start/end properties in the resulting AST nods.

Yes, at the moment I think this is the easiest way to accomplish the goal here. There's an example of how to use the parser to get location information [in the usage section of its readme](https://github.com/shapesecurity/shift-parser-js/#usage).

> what does `rep` stand for, please

"representation"

**Comment by michaelficarra** [comment]
@mightyiam You might be interested in [the scope analyser demo](http://shift-ast.org/scope.html) which had similar goals.

**Comment by bakkot** [comment]
Fixed by #71.

This is available in v5.1.0. Let us know if it works for you!
