### ISSUE TITLE
Performance: degradation linked to generated source size & targeting es2015

### ISSUE THREAD

**Issue by jsoverson** [shapesecurity/shift-codegen-js#87]
Every time another token is added, TokenStream checks the end of what it has already generated to avoid creating an HTML comment ([L:105](https://github.com/shapesecurity/shift-codegen-js/blob/es2018/src/token-stream.js#L105)). This blows up as source size increases. Generating 547k of js takes ~120 seconds on a recent MacBook and with a more focused check it drops to ~4 seconds. Reducing the number of babel transforms drops runtime further to ~0.3 seconds.

I can submit a PR for any combination of the above. Getting rid of the `endsWith()` check is important, but limiting or removing babel would give the best performance gains.

**Comment by bakkot** [comment]
> a more focused check

Sounds good to me. It's a shame engines aren't optimizing that better; there's many string representations which wouldn't have that problem.

> Reducing the number of babel transforms

I think in the next major version we should drop support for EOL versions of node, which would let us drop babel (almost?) entirely. But that's most easily done at major version bumps.

**Comment by bakkot** [comment]
Gonna call this fixed between https://github.com/shapesecurity/shift-codegen-js/pull/88 and https://github.com/shapesecurity/shift-codegen-js/commit/74746831dc675b968e83bff14a1de9821e643307 (which dropped babel, released in 8.0.0). Feel free to reopen if there's still performance issues.
